# Generated by Django 4.2.10 on 2024-02-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(max_length=255)),
                ('petSize', models.CharField(max_length=255)),
                ('petAge', models.CharField(max_length=255)),
                ('petPersonality', models.CharField(max_length=255)),
                ('tripConcept', models.CharField(max_length=255)),
            ],
        ),
    ]
